# Generated by Django 4.0.4 on 2022-04-20 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_membro', models.CharField(max_length=100)),
                ('bando', models.CharField(max_length=200)),
                ('função', models.CharField(max_length=200)),
                ('akuma_no_mi', models.CharField(max_length=100)),
                ('foto_membro', models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y')),
                ('data_membro', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
