# Generated by Django 4.0.4 on 2022-04-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_bando', models.CharField(max_length=100)),
                ('quantidade_membros', models.IntegerField()),
            ],
        ),
    ]
