# Generated by Django 4.0.4 on 2022-04-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0002_bando'),
    ]

    operations = [
        migrations.AddField(
            model_name='bando',
            name='foto_bando',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y'),
        ),
    ]
