# Generated by Django 4.0.4 on 2022-04-24 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0003_bando_foto_bando'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membro',
            name='bando',
        ),
        migrations.AddField(
            model_name='membro',
            name='membro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='membros.bando'),
            preserve_default=False,
        ),
    ]
