# Generated by Django 4.0.4 on 2022-04-24 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0004_remove_membro_bando_membro_membro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membro',
            old_name='membro',
            new_name='bando',
        ),
    ]
