# Generated by Django 4.0.4 on 2022-04-26 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0007_bando_quantidade_membros'),
    ]

    operations = [
        migrations.CreateModel(
            name='AkumaNoMi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fruta', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Logia', 'Logia'), ('Paramecia', 'Paramecia'), ('Zoan', 'Zoan')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='membro',
            name='akuma_no_mi',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='membros.akumanomi'),
        ),
    ]
