# Generated by Django 4.0.4 on 2022-04-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0008_akumanomi_alter_membro_akuma_no_mi'),
    ]

    operations = [
        migrations.AddField(
            model_name='akumanomi',
            name='foto_akuma',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y'),
        ),
    ]
